# PLEASE NOTE THIS ENTIRE SCRIPT HAS BEEN GENERATED BY GEMINI USE WITH CAUTION
# See render_laters.ipynb for data.txt format
# run via:
#   docker run --rm -it -v /home/user/embeddings:/manim manimcommunity/manim manim -qm zoom_video.py FinalZoomAnimation

from manim import *
import numpy as np

class FinalZoomAnimation(MovingCameraScene):
    def construct(self):
        self.camera.background_color = WHITE
        
        # 1. Viewport Definitions
        x_wide, y_wide = [-3, 28, 2], [-4, 8, 1]
        x_zoom_target = [4, 7]
        y_zoom_target = [5.75, 6.25]

        # 2. Create the Grid
        grid = NumberPlane(
            x_range=x_wide, y_range=y_wide,
            background_line_style={"stroke_color": LIGHT_GRAY, "stroke_opacity": 0.5, "stroke_width": 1},
            axis_config={"stroke_color": LIGHT_GRAY, "stroke_opacity": 0.8, "stroke_width": 2, "include_ticks": False}
        ).scale_to_fit_width(config.frame_width - 1)

        # 3. Data Parsing
        frames = {}
        unique_words = set()
        word_colors = {}
        try:
            with open("data.txt", "r") as f:
                for line in f:
                    if not line.strip(): continue
                    parts = line.strip().split(" ")
                    f_idx, word, color_str = int(parts[0]), parts[1], parts[2].upper()
                    coords = [float(c) for c in parts[3].split(",")]
                    if f_idx not in frames: frames[f_idx] = {}
                    frames[f_idx][word] = grid.c2p(coords[0], coords[1])
                    unique_words.add(word)
                    word_colors[word] = globals().get(color_str, BLACK)
        except Exception as e: print(f"Data Error: {e}"); return

        # 4. Static Data Parsing
        static_data = []
        try:
            with open("staticwords.txt", "r") as f:
                for line in f:
                    if not line.strip(): continue
                    parts = line.strip().split(" ")
                    word, color_str = parts[1], parts[2].upper()
                    coords = [float(c) for c in parts[3].split(",")]
                    static_data.append({
                        "word": word, 
                        "color": globals().get(color_str, BLACK), 
                        "pos": grid.c2p(coords[0], coords[1])
                    })
        except Exception: pass

        # 5. Mobjects Logic
        dots_pos_trackers = {}
        sorted_indices = sorted(frames.keys())
        layer_tracker = ValueTracker(sorted_indices[0])
        
        def get_zoom_ratio():
            return self.camera.frame.get_width() / config.frame_width

        layer_display = always_redraw(lambda: 
            Text(f"Layer: {int(layer_tracker.get_value()) + 1:02d}", 
                 font="sans-serif", font_size=24, color=BLACK
            ).scale(get_zoom_ratio())
             .move_to(self.camera.frame.get_corner(UL) + (RIGHT*1.5 + DOWN*0.6) * get_zoom_ratio())
        )

        for word in unique_words:
            pos = frames[sorted_indices[0]].get(word, grid.c2p(0, 0))
            color = word_colors[word]
            pos_tracker = Dot(point=pos, radius=0).set_opacity(0)
            dots_pos_trackers[word] = pos_tracker
            
            dot = always_redraw(lambda pt=pos_tracker, c=color: 
                Dot(point=pt.get_center(), color=c, radius=0.08 * get_zoom_ratio())
            )
            
            label = always_redraw(lambda d=dot, w=word: 
                Text(w, font="sans-serif", font_size=18, color=BLACK)
                .scale(get_zoom_ratio())
                .next_to(d, UR, buff=0)
                .shift((RIGHT * 0.05 + UP * 0.025) * get_zoom_ratio()) 
            )
            self.add(pos_tracker, dot, label)

        self.add(grid, layer_display)

        # 6. Main Animation Loop (Movement Only) - SPEED DOUBLED
        for i in range(1, len(sorted_indices)):
            current_idx = sorted_indices[i]
            target_data = frames[current_idx]
            
            self.play(
                *[dots_pos_trackers[word].animate.move_to(target_data[word]) 
                  for word in dots_pos_trackers if word in target_data],
                layer_tracker.animate.set_value(current_idx),
                run_time=0.5, # Reduced from 1.0
                rate_func=linear
            )

        # 7. Final Static Layer Appearance - SPEED DOUBLED
        static_group = VGroup()
        if static_data:
            for obj in static_data:
                s_dot_tracker = Dot(point=obj["pos"], radius=0).set_opacity(0)
                s_dot = always_redraw(lambda pt=s_dot_tracker, c=obj["color"]: 
                    Dot(point=pt.get_center(), color=c, radius=0.08 * get_zoom_ratio())
                )
                s_label = always_redraw(lambda d=s_dot, w=obj["word"]: 
                    Text(w, font="sans-serif", font_size=18, color=BLACK)
                    .scale(get_zoom_ratio())
                    .next_to(d, DL, buff=0)
                    .shift((LEFT * 0.05 + DOWN * 0.025) * get_zoom_ratio())
                )
                static_group.add(s_dot_tracker, s_dot, s_label)
            
            self.play(FadeIn(static_group), run_time=0.5) # Reduced from 1.0
            self.wait(0.5) # Reduced from 1.0

        # 8. Post-Static Zoom - SPEED DOUBLED
        p1, p2 = grid.c2p(x_zoom_target[0], y_zoom_target[0]), grid.c2p(x_zoom_target[1], y_zoom_target[1])
        target_center = (p1 + p2) / 2
        target_width = abs(p2[0] - p1[0]) * 2.7 

        self.play(
            self.camera.frame.animate.move_to(target_center).set_width(target_width),
            run_time=1.5, # Reduced from 3.0
            rate_func=smooth
        )

        self.wait(2)
